travis:
  secure:
    BINSTAR_TOKEN: Dq8vknzmatm7IfPLJv6YQyIjfXj6QM788kVsyNGgaqAFNkaof+dajDfDCZAUFFETNBKawNxHZDmPhO3QrFKA1RWBJLuq6xe6lRHetCooT0DC25BcQPfxWLN7WICBvHsdAkgut3thnW1dwWMCudf9k5TC9Saf3nT/z/18sZVcAh2Jsg+epW4GXl7KtUK0IW2tu4GF2U3Pa+W0Z45dDOHIbz7i5OOiOZKmHairyW88DyqHHpS5m3eLUq1sS/AX7uK4217WZE4YFeFjU/k4YqJNeLpWX9Bomx4bIdj8n4ygsgGwZGY2gtaAW+NB3QvNh2YoxgN1G5uF8MNujyVGU5Js+xKtBKDWmbWa8oK1zXuIvMDlBCD0qIYraXjaWpbG/KJmjaknJV0IOM68I7m0d9o1PF740AdeFsjJ/8TQhGs1cYBmHVUXta98TLDTFrzSeEFYq7nWb2mv6ekiQOvVKUO4fUJYnXVC5ic18Y02OuYefGv1lJzGXVypSu06bBEa+itpF/7+nUAhHGNAYZPbwc2yjTuKqzGRYRI9vSRHTNNn+E87+l/g/fwkeuNzf9a3+XIkXjJsQ5aKo1GR/5gpNll63LemQdSun0WjKgZQf4WBZDqEfUNaEXH2R0cTI+4HOwjRpmnkNY7zok8+tIINhxmf+tbmMMYkWONCeQdqriAq+a8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
