travis:
  secure:
    BINSTAR_TOKEN: XQXiFBBmNhTYnMojVEODZymxhVehGb4/1F0VaxQ1cS5HlyI8vS7rnE9XfvzxozAP48ul7Q8scthwrS/GCPCQIytLC8tSAKgf9TksTLQsdog3khHlex8bBJTZ9OH53JPVov4qPh1b0Apob3JZzYCkQv8xs3gnrd7OG+6HyjZbFU12JclS12IY7HS5mySF5t3XAMVlRWVN6E1fZVrIdT8NLxLd4XNp5ArfZnflOsBJcuXBB5USUz0vm9Vsu/B92bhJKAdjvjXLZS+Xz6TJKsFgAXLFP1TbQoTu5soR3xXf3J/3NzsvkSgHELLNXX98h+5HMohfJLFB2yOc59OsaG7/ssmCRBFOlcYNZlJ/bScD7iVjg0VBKXaefXKcc3z26+W4en6Ab2rJ0vuj51DoYuaZ1PBYIxHu7dwelHEMeY8kwhX9ea80vJs+iDnR15ajPkFPAjvNJf9FPGOG45i3pcx5eUPgy60oFHB9PMxexNJ0zIGHjxc/Iu1JLtFGqp2XXsBO3rDjBqrTE6ZCh+bQdHiGOyEu+zluR5HK/cYijsaCUTlZYhroWZrmC3LeYZ4jjRAYeZbf+syUfSxFtvDLf3El1olxNoUqA65Wn/QFQKCn7uzhQOFNUIlAMqTzqPsNn99ip5IJMabUcybadmJO2MFOD71WhyxLkHMhD6i8mHw06n0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
