travis:
  secure:
    BINSTAR_TOKEN: R9NuWvu4mO1OMxRZQX/SBnAZzKPRmlRceq6EA4/wYwe0+Ilc2XYU2IT6h8PtDYQd8uBxc6743/NgvSyKJR5gT4OlT/+Qi5SrQzOjIMlt7qrjaHCx1Lk63cpmR5qAtBjyFInHL/w0ilsuwDiIwUGnqA8GEg8DvCv9+j6hQWC2rMwcJTLSG2chxWQ4FFxzGfOoUrH8lQYCJM47uD+2dl1xiFZ5kcA7mpHf+AEk5iOYlYlzzUfMLaQ2aKFS4AYXcOlTm+7TFYFNyGUj76FYY0hZu6avZU7zTEk9y4yjAYadTrWLqaG8Bj8rbbpOdAIPpHxxM5z5bOy2pxVL5dCeQF3U6XNLi1lKtq64F3GhjunfPhw/1c0Rd93JA0Rc64XA92PIF+HZ6IqEbSMZsh0MOlJIf0jZKA+/7JR0CJykq9fktKuNsf/XZoFmsJbosFmjijfnRGqTLkHCSAZI85MmBvQ/QNMysJHDqU5kRxPsStNL+jjd5oeWHA9oZWtnFULyu2WP2SZvpHRoigBjYXGL3/OyQISRALB6cz7pRP3YNlAns8/oVrINPYAnXwjLcoBDC26ln5OzccJn/7TUj2+gQe4eqDMsKGFUQXCSJtYpbpa2Ie3g8ejczV6SPEO7l540fiPc+Ya9s5JBIuvKAc6jPXlqZwhyaorQux9Yn0rvLCvGwk8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
