travis:
  secure:
    BINSTAR_TOKEN: I4OIw4+C3WayUECPf7bK8NB8ecOma/NEDtpsw6X7C7/mo9GL/j8sWPeklvIuBN/gO4HAjQ99ATv7qWgn33/yFm9Dy3Y3QZ4moLWholooXVCWvPZWE8gaChDl8HBbKif5wLBpF8vJJ5Bs2k6Lsbu13J/hqgDUTogYZSYnR3KtY/tqLKMzmv8wk4Jjjz2O7wfoN6ZF9Ovs6NBjaIFEvELoWrYHeUmRiseQZOW3CoM6NEtR6iNSycEtW62UHqu8uuZlV1dbNPdP8A3YRwGSWYtyIayO+ELCx777P9RTxTQwGd/8BTZg+CLIRWRzccByNsYtqAdqek4zJ3ywty3YbWkfizUFVUxqhuDy0lhnL8taduZ5SrNZokHUBFib3deAsmWlYtwhp9a5V2T47BbqFVzxwbGqn0eJiUsQdXKPvr10tu2r6Z8kKjuFvQZbNWU60YhfLVFfDxfrcadL0EPKb5a5HMAqL90P/x4kQdgy26Ha5h5g/pr/0PtVwDX8JJKKc9oZToLDUiv/YqQ2iP8MIWNRYAnc0H8t/DmZ/UXPmtvmVrUOn16nBJtkPgxwYB7ERdj3CQQu7YCA8MUNNyDmkrYE5TH6PRWlvp3gDBFM2FSbnn9t3uiC8s0+0DAM8BiulQTFo3KcT8ZIfn+8A+zH9Q5qdu/kqmHgNzw/y+2yb0RdJH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
