travis:
  secure:
    BINSTAR_TOKEN: BUv1flnvapomYZR2bwWfE1Prl8tQwqncqKs8gpw8aSUENmz2tNV20JR59jGY5rOqnhAl2EmQOBUDgEd+lse7W0bze76vFlPpopRcDD81vgcc8ZZt9CUxiffCcFbKik6ppcD1mdef6E3WaqmbIQzCz4whdg68LPaMFovdEO+wIRhebdlQaZ39NL/XgthzS88YzwGG15tGMvDnJpTkjzAAE8Cs4VVjM8jy0tD6w7gV/2CNQ6mPNiSgPlo2D2mh1mhob5J/qhQclFLwu0BsNOHPnhL/UKZJuAxUZX27PQVYuAP87b5vrqr7uC3+ld33kRA3Mn48cMDHropMaXvlNkCOC210LrExVqVtyLOTbOAoKdU5Ls4ZNW9c2MNufGGtGMUiVux7CeTyJkjO8uxMocyU1EyQmtcFu/ybFC8ZCSs5/gSXqzJqYpz0GyZoBpjRRa+iSwk2wj9veri3V2hrifCGuDaP7NkEh4G+KSH55C/dOoHMqiCW8N4lIonCHh4WxfMkirOgDHY0PptZ34LJJuMVTnzB4HIoZtLfaNpIsEmkoAKqcXC9r8En7qbS3Zlroc4x9Kfs5UMP5Ot1vPgiqefZlciOvmzZI1SITzkkQmbGWYia6g8LovYVp71zFic3g7tO43qSRzZJvR95Qzadn4/+G9jFCcZQDYl63EDVobrMDJs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
